#!/usr/bin/env python3
"""
LEGACY HELPER — NOT THE PREFERRED WORKFLOW.

This script auto-chunks pages and calls generate_md_draft.py repeatedly.
Because that means chunking decisions are partly script-driven, this is not the
recommended workflow anymore.

Prefer:
1. extract assets
2. let the model read a small chunk directly
3. let the model decide chunk boundaries
4. write the chunk mechanically with write_md_chunk.py
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import List, Tuple


HEADING_RE = re.compile(r"(?m)^((?:\d+\.)+(?:\d+)?\s+[^\n]+|\d+\.\s+[^\n]+)$")


def detect_total_pages(extracted_text: Path) -> int:
    text = extracted_text.read_text(encoding="utf-8", errors="ignore")
    nums = [int(x) for x in re.findall(r"(?m)^===== PAGE (\d+) =====$", text)]
    if not nums:
        return 0
    return max(nums)


def split_pages(extracted_text: Path) -> List[Tuple[int, str]]:
    text = extracted_text.read_text(encoding="utf-8", errors="ignore")
    parts = re.split(r"(?m)^===== PAGE (\d+) =====\n?", text)
    pages: List[Tuple[int, str]] = []
    for i in range(1, len(parts), 2):
        pno = int(parts[i])
        body = parts[i + 1].strip()
        pages.append((pno, body))
    return pages


def normalize_page_text(text: str) -> str:
    text = text.replace("-\n", "")
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def detect_section_ranges(extracted_text: Path) -> List[Tuple[int, int, str]]:
    pages = split_pages(extracted_text)
    if not pages:
        return []

    anchors: List[Tuple[int, str]] = [(pages[0][0], "起始部分")]
    for pno, body in pages:
        cleaned = normalize_page_text(body)
        for m in HEADING_RE.finditer(cleaned):
            title = m.group(1).strip()
            anchors.append((pno, title))
            break

    # deduplicate same-page anchors, keep first meaningful one
    compact: List[Tuple[int, str]] = []
    seen_pages = set()
    for pno, title in anchors:
        if pno in seen_pages:
            continue
        compact.append((pno, title))
        seen_pages.add(pno)

    ranges: List[Tuple[int, int, str]] = []
    for i, (start, title) in enumerate(compact):
        end = compact[i + 1][0] - 1 if i + 1 < len(compact) else pages[-1][0]
        if end < start:
            end = start
        ranges.append((start, end, title))
    return ranges


def expand_ranges(ranges: List[Tuple[int, int, str]], chunk_size: int) -> List[Tuple[int, int, str]]:
    out: List[Tuple[int, int, str]] = []
    for start, end, title in ranges:
        if end - start + 1 <= chunk_size:
            out.append((start, end, title))
            continue
        part = 1
        for s in range(start, end + 1, chunk_size):
            e = min(s + chunk_size - 1, end)
            out.append((s, e, f"{title}（第{part}段）"))
            part += 1
    return out


def main():
    ap = argparse.ArgumentParser(
        description="LEGACY helper: auto-generate markdown in chunks. "
        "Not recommended as the main workflow; prefer model-decided chunks + write_md_chunk.py."
    )
    ap.add_argument("--assets-dir", required=True, help="Directory generated by extract_pdf_assets.py")
    ap.add_argument("--out-md", required=True, help="Final markdown output path")
    ap.add_argument("--title", default="论文", help="Markdown title")
    ap.add_argument("--chunk-size", type=int, default=2, help="Pages per chunk, default 2")
    ap.add_argument("--start-page", type=int, default=1, help="Start page for chunked generation")
    ap.add_argument("--end-page", type=int, help="End page for chunked generation; default is last page")
    ap.add_argument("--strategy", choices=["pages", "section-first"], default="section-first", help="Chunking strategy")
    args = ap.parse_args()

    assets_dir = Path(args.assets_dir)
    extracted = assets_dir / "extracted_text.txt"
    if not extracted.exists():
        raise FileNotFoundError(f"missing: {extracted}")

    total_pages = detect_total_pages(extracted)
    if total_pages <= 0:
        raise RuntimeError("could not detect page count from extracted_text.txt")

    end_page = args.end_page or total_pages
    out_md = Path(args.out_md)
    if out_md.exists():
        out_md.unlink()

    gen_script = Path(__file__).with_name("generate_md_draft.py")

    if args.strategy == "section-first":
        ranges = [
            (s, e, t)
            for s, e, t in detect_section_ranges(extracted)
            if e >= args.start_page and s <= end_page
        ]
        ranges = [(max(s, args.start_page), min(e, end_page), t) for s, e, t in ranges]
        ranges = [(s, e, t) for s, e, t in ranges if s <= e]
        if not ranges:
            ranges = [(start, min(start + args.chunk_size - 1, end_page), f"P{start}-{min(start + args.chunk_size - 1, end_page)}")
                      for start in range(args.start_page, end_page + 1, args.chunk_size)]
        ranges = expand_ranges(ranges, args.chunk_size)
    else:
        ranges = [
            (start, min(start + args.chunk_size - 1, end_page), f"P{start}-{min(start + args.chunk_size - 1, end_page)}")
            for start in range(args.start_page, end_page + 1, args.chunk_size)
        ]

    chunk_idx = 1
    for start, end, title in ranges:
        cmd = [
            sys.executable,
            str(gen_script),
            "--assets-dir",
            str(assets_dir),
            "--out-md",
            str(out_md),
            "--title",
            args.title,
            "--start-page",
            str(start),
            "--end-page",
            str(end),
            "--mode",
            "pages",
        ]
        if chunk_idx > 1:
            cmd += ["--append", "--chunk-label", f"第{chunk_idx}块：{title}（P{start}-P{end}）"]
        print("running:", " ".join(cmd))
        subprocess.run(cmd, check=True)
        chunk_idx += 1

    print(f"done: chunked markdown written to {out_md}")


if __name__ == "__main__":
    main()
